environment          = "dev"
aws_region           = "us-east-1"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.1.0/20", "10.0.2.0/20", "10.0.3.0/20"]
private_subnet_cidrs = ["10.0.16.0/18", "10.0.80.0/18", "10.0.144.0/18"]
single_nat_gateway   = true
cluster_version      = "1.28"
on_demand_instance_types = ["t3.medium"]
on_demand_desired_size   = 2
on_demand_min_size       = 1
on_demand_max_size       = 4
enable_spot_node_group   = false
instance_class           = "db.r6g.large"
aurora_reader_count      = 0
redis_node_type          = "cache.r6g.large"
redis_num_nodes          = 1
alert_email              = "devops@longox.io"
root_domain              = "longox.io"
deploy_vault             = true
vault_auto_unseal        = false
deploy_kong              = true
enable_cross_region_replication = false
