import type { EventType } from "./events";

export interface EventRegistryEntry {
  specVersion: string;
  dataSchema: string;
  description: string;
  category: "workflow" | "execution" | "connector" | "ai" | "billing" | "audit" | "search" | "platform";
  critical: boolean;
  retentionDays: number;
}

export const EVENT_REGISTRY: Record<EventType, EventRegistryEntry> = {
  "workflow.created": {
    specVersion: "1.0",
    dataSchema: "workflow.created.v1",
    description: "A workflow was created",
    category: "workflow",
    critical: false,
    retentionDays: 90,
  },
  "workflow.updated": {
    specVersion: "1.0",
    dataSchema: "workflow.updated.v1",
    description: "A workflow was updated",
    category: "workflow",
    critical: false,
    retentionDays: 90,
  },
  "workflow.deleted": {
    specVersion: "1.0",
    dataSchema: "workflow.deleted.v1",
    description: "A workflow was deleted",
    category: "workflow",
    critical: false,
    retentionDays: 90,
  },
  "workflow.published": {
    specVersion: "1.0",
    dataSchema: "workflow.published.v1",
    description: "A workflow version was published to an environment",
    category: "workflow",
    critical: true,
    retentionDays: 365,
  },
  "workflow.version.created": {
    specVersion: "1.0",
    dataSchema: "workflow.version.created.v1",
    description: "A new workflow version was created",
    category: "workflow",
    critical: false,
    retentionDays: 90,
  },
  "workflow.promoted": {
    specVersion: "1.0",
    dataSchema: "workflow.promoted.v1",
    description: "A workflow was promoted between environments",
    category: "workflow",
    critical: true,
    retentionDays: 365,
  },
  "workflow.rolled_back": {
    specVersion: "1.0",
    dataSchema: "workflow.rolled_back.v1",
    description: "A workflow was rolled back to a previous version",
    category: "workflow",
    critical: true,
    retentionDays: 365,
  },
  "execution.started": {
    specVersion: "1.0",
    dataSchema: "execution.started.v1",
    description: "A workflow execution started",
    category: "execution",
    critical: true,
    retentionDays: 30,
  },
  "execution.completed": {
    specVersion: "1.0",
    dataSchema: "execution.completed.v1",
    description: "A workflow execution completed successfully",
    category: "execution",
    critical: false,
    retentionDays: 30,
  },
  "execution.failed": {
    specVersion: "1.0",
    dataSchema: "execution.failed.v1",
    description: "A workflow execution failed",
    category: "execution",
    critical: true,
    retentionDays: 90,
  },
  "execution.cancelled": {
    specVersion: "1.0",
    dataSchema: "execution.cancelled.v1",
    description: "A workflow execution was cancelled",
    category: "execution",
    critical: false,
    retentionDays: 30,
  },
  "execution.timeout": {
    specVersion: "1.0",
    dataSchema: "execution.timeout.v1",
    description: "A workflow execution timed out",
    category: "execution",
    critical: true,
    retentionDays: 90,
  },
  "execution.node.started": {
    specVersion: "1.0",
    dataSchema: "execution.node.started.v1",
    description: "A workflow node started execution",
    category: "execution",
    critical: false,
    retentionDays: 14,
  },
  "execution.node.completed": {
    specVersion: "1.0",
    dataSchema: "execution.node.completed.v1",
    description: "A workflow node completed execution",
    category: "execution",
    critical: false,
    retentionDays: 14,
  },
  "execution.node.failed": {
    specVersion: "1.0",
    dataSchema: "execution.node.failed.v1",
    description: "A workflow node failed execution",
    category: "execution",
    critical: true,
    retentionDays: 90,
  },
  "execution.node.paused": {
    specVersion: "1.0",
    dataSchema: "execution.node.paused.v1",
    description: "A workflow node was paused for approval",
    category: "execution",
    critical: false,
    retentionDays: 30,
  },
  "execution.node.resumed": {
    specVersion: "1.0",
    dataSchema: "execution.node.resumed.v1",
    description: "A paused workflow node was resumed",
    category: "execution",
    critical: false,
    retentionDays: 30,
  },
  "execution.approval.required": {
    specVersion: "1.0",
    dataSchema: "execution.approval.required.v1",
    description: "Human approval is required to proceed",
    category: "execution",
    critical: true,
    retentionDays: 90,
  },
  "execution.approval.granted": {
    specVersion: "1.0",
    dataSchema: "execution.approval.granted.v1",
    description: "An approval request was granted",
    category: "execution",
    critical: false,
    retentionDays: 90,
  },
  "execution.approval.rejected": {
    specVersion: "1.0",
    dataSchema: "execution.approval.rejected.v1",
    description: "An approval request was rejected",
    category: "execution",
    critical: false,
    retentionDays: 90,
  },
  "connector.installed": {
    specVersion: "1.0",
    dataSchema: "connector.installed.v1",
    description: "A connector was installed",
    category: "connector",
    critical: true,
    retentionDays: 365,
  },
  "connector.uninstalled": {
    specVersion: "1.0",
    dataSchema: "connector.uninstalled.v1",
    description: "A connector was uninstalled",
    category: "connector",
    critical: false,
    retentionDays: 365,
  },
  "connector.configured": {
    specVersion: "1.0",
    dataSchema: "connector.configured.v1",
    description: "A connector configuration was updated",
    category: "connector",
    critical: false,
    retentionDays: 90,
  },
  "connector.upgraded": {
    specVersion: "1.0",
    dataSchema: "connector.upgraded.v1",
    description: "A connector was upgraded to a new version",
    category: "connector",
    critical: false,
    retentionDays: 365,
  },
  "connector.rolled_back": {
    specVersion: "1.0",
    dataSchema: "connector.rolled_back.v1",
    description: "A connector was rolled back to a previous version",
    category: "connector",
    critical: true,
    retentionDays: 365,
  },
  "connector.execution.started": {
    specVersion: "1.0",
    dataSchema: "connector.execution.started.v1",
    description: "A connector action execution started",
    category: "connector",
    critical: false,
    retentionDays: 30,
  },
  "connector.execution.completed": {
    specVersion: "1.0",
    dataSchema: "connector.execution.completed.v1",
    description: "A connector action execution completed",
    category: "connector",
    critical: false,
    retentionDays: 30,
  },
  "connector.execution.failed": {
    specVersion: "1.0",
    dataSchema: "connector.execution.failed.v1",
    description: "A connector action execution failed",
    category: "connector",
    critical: true,
    retentionDays: 90,
  },
  "connector.webhook.received": {
    specVersion: "1.0",
    dataSchema: "connector.webhook.received.v1",
    description: "A webhook was received from a connector",
    category: "connector",
    critical: false,
    retentionDays: 30,
  },
  "connector.test.completed": {
    specVersion: "1.0",
    dataSchema: "connector.test.completed.v1",
    description: "A connector test execution completed",
    category: "connector",
    critical: false,
    retentionDays: 14,
  },
  "ai.run.started": {
    specVersion: "1.0",
    dataSchema: "ai.run.started.v1",
    description: "An AI model run started",
    category: "ai",
    critical: false,
    retentionDays: 30,
  },
  "ai.run.completed": {
    specVersion: "1.0",
    dataSchema: "ai.run.completed.v1",
    description: "An AI model run completed",
    category: "ai",
    critical: false,
    retentionDays: 30,
  },
  "ai.run.failed": {
    specVersion: "1.0",
    dataSchema: "ai.run.failed.v1",
    description: "An AI model run failed",
    category: "ai",
    critical: false,
    retentionDays: 90,
  },
  "ai.run.blocked": {
    specVersion: "1.0",
    dataSchema: "ai.run.blocked.v1",
    description: "An AI model run was blocked by guardrails",
    category: "ai",
    critical: true,
    retentionDays: 90,
  },
  "ai.guardrail.hit": {
    specVersion: "1.0",
    dataSchema: "ai.guardrail.hit.v1",
    description: "An AI guardrail was triggered",
    category: "ai",
    critical: false,
    retentionDays: 90,
  },
  "ai.budget.exceeded": {
    specVersion: "1.0",
    dataSchema: "ai.budget.exceeded.v1",
    description: "AI budget threshold was exceeded",
    category: "ai",
    critical: true,
    retentionDays: 90,
  },
  "ai.evaluation.passed": {
    specVersion: "1.0",
    dataSchema: "ai.evaluation.passed.v1",
    description: "An AI evaluation passed",
    category: "ai",
    critical: false,
    retentionDays: 30,
  },
  "ai.evaluation.failed": {
    specVersion: "1.0",
    dataSchema: "ai.evaluation.failed.v1",
    description: "An AI evaluation failed",
    category: "ai",
    critical: false,
    retentionDays: 30,
  },
  "ai.prompt.created": {
    specVersion: "1.0",
    dataSchema: "ai.prompt.created.v1",
    description: "An AI prompt was created",
    category: "ai",
    critical: false,
    retentionDays: 90,
  },
  "ai.prompt.promoted": {
    specVersion: "1.0",
    dataSchema: "ai.prompt.promoted.v1",
    description: "An AI prompt was promoted to production",
    category: "ai",
    critical: true,
    retentionDays: 365,
  },
  "billing.invoice.created": {
    specVersion: "1.0",
    dataSchema: "billing.invoice.created.v1",
    description: "A billing invoice was created",
    category: "billing",
    critical: true,
    retentionDays: 730,
  },
  "billing.invoice.paid": {
    specVersion: "1.0",
    dataSchema: "billing.invoice.paid.v1",
    description: "A billing invoice was paid",
    category: "billing",
    critical: true,
    retentionDays: 730,
  },
  "billing.invoice.failed": {
    specVersion: "1.0",
    dataSchema: "billing.invoice.failed.v1",
    description: "A billing invoice payment failed",
    category: "billing",
    critical: true,
    retentionDays: 730,
  },
  "billing.subscription.created": {
    specVersion: "1.0",
    dataSchema: "billing.subscription.created.v1",
    description: "A billing subscription was created",
    category: "billing",
    critical: true,
    retentionDays: 730,
  },
  "billing.subscription.updated": {
    specVersion: "1.0",
    dataSchema: "billing.subscription.updated.v1",
    description: "A billing subscription was updated",
    category: "billing",
    critical: true,
    retentionDays: 730,
  },
  "billing.subscription.cancelled": {
    specVersion: "1.0",
    dataSchema: "billing.subscription.cancelled.v1",
    description: "A billing subscription was cancelled",
    category: "billing",
    critical: true,
    retentionDays: 730,
  },
  "billing.plan.entitlement.exceeded": {
    specVersion: "1.0",
    dataSchema: "billing.plan.entitlement.exceeded.v1",
    description: "A plan entitlement limit was exceeded",
    category: "billing",
    critical: false,
    retentionDays: 90,
  },
  "billing.overage.incurred": {
    specVersion: "1.0",
    dataSchema: "billing.overage.incurred.v1",
    description: "Usage overage was incurred",
    category: "billing",
    critical: false,
    retentionDays: 90,
  },
  "audit.action.executed": {
    specVersion: "1.0",
    dataSchema: "audit.action.executed.v1",
    description: "An auditable action was executed",
    category: "audit",
    critical: true,
    retentionDays: 730,
  },
  "audit.export.created": {
    specVersion: "1.0",
    dataSchema: "audit.export.created.v1",
    description: "An audit log export was created",
    category: "audit",
    critical: false,
    retentionDays: 365,
  },
  "search.index.updated": {
    specVersion: "1.0",
    dataSchema: "search.index.updated.v1",
    description: "A search index was updated",
    category: "search",
    critical: false,
    retentionDays: 14,
  },
  "search.reindex.started": {
    specVersion: "1.0",
    dataSchema: "search.reindex.started.v1",
    description: "A full search reindex started",
    category: "search",
    critical: false,
    retentionDays: 30,
  },
  "search.reindex.completed": {
    specVersion: "1.0",
    dataSchema: "search.reindex.completed.v1",
    description: "A full search reindex completed",
    category: "search",
    critical: false,
    retentionDays: 30,
  },
  "platform.tenant.created": {
    specVersion: "1.0",
    dataSchema: "platform.tenant.created.v1",
    description: "A new tenant was created on the platform",
    category: "platform",
    critical: true,
    retentionDays: 365,
  },
  "platform.tenant.updated": {
    specVersion: "1.0",
    dataSchema: "platform.tenant.updated.v1",
    description: "A tenant configuration was updated",
    category: "platform",
    critical: false,
    retentionDays: 365,
  },
  "platform.tenant.deleted": {
    specVersion: "1.0",
    dataSchema: "platform.tenant.deleted.v1",
    description: "A tenant was deleted from the platform",
    category: "platform",
    critical: true,
    retentionDays: 365,
  },
  "platform.user.invited": {
    specVersion: "1.0",
    dataSchema: "platform.user.invited.v1",
    description: "A user was invited to the platform",
    category: "platform",
    critical: false,
    retentionDays: 90,
  },
  "platform.user.joined": {
    specVersion: "1.0",
    dataSchema: "platform.user.joined.v1",
    description: "A user joined the platform",
    category: "platform",
    critical: false,
    retentionDays: 90,
  },
  "platform.user.removed": {
    specVersion: "1.0",
    dataSchema: "platform.user.removed.v1",
    description: "A user was removed from the platform",
    category: "platform",
    critical: false,
    retentionDays: 365,
  },
  "platform.region.health.changed": {
    specVersion: "1.0",
    dataSchema: "platform.region.health.changed.v1",
    description: "A platform region health status changed",
    category: "platform",
    critical: true,
    retentionDays: 365,
  },
  "platform.backup.completed": {
    specVersion: "1.0",
    dataSchema: "platform.backup.completed.v1",
    description: "A platform backup completed",
    category: "platform",
    critical: true,
    retentionDays: 365,
  },
  "platform.backup.failed": {
    specVersion: "1.0",
    dataSchema: "platform.backup.failed.v1",
    description: "A platform backup failed",
    category: "platform",
    critical: true,
    retentionDays: 365,
  },
  "platform.restore.completed": {
    specVersion: "1.0",
    dataSchema: "platform.restore.completed.v1",
    description: "A platform restore completed",
    category: "platform",
    critical: true,
    retentionDays: 365,
  },
  "platform.restore.failed": {
    specVersion: "1.0",
    dataSchema: "platform.restore.failed.v1",
    description: "A platform restore failed",
    category: "platform",
    critical: true,
    retentionDays: 365,
  },
  "platform.rollback.completed": {
    specVersion: "1.0",
    dataSchema: "platform.rollback.completed.v1",
    description: "A platform rollback completed",
    category: "platform",
    critical: true,
    retentionDays: 365,
  },
  "platform.migration.started": {
    specVersion: "1.0",
    dataSchema: "platform.migration.started.v1",
    description: "A platform tenant migration started",
    category: "platform",
    critical: true,
    retentionDays: 365,
  },
  "platform.migration.completed": {
    specVersion: "1.0",
    dataSchema: "platform.migration.completed.v1",
    description: "A platform tenant migration completed",
    category: "platform",
    critical: true,
    retentionDays: 365,
  },
  "platform.migration.failed": {
    specVersion: "1.0",
    dataSchema: "platform.migration.failed.v1",
    description: "A platform tenant migration failed",
    category: "platform",
    critical: true,
    retentionDays: 365,
  },
  "platform.certificate.expiring": {
    specVersion: "1.0",
    dataSchema: "platform.certificate.expiring.v1",
    description: "A platform certificate is nearing expiration",
    category: "platform",
    critical: true,
    retentionDays: 90,
  },
};
