environment          = "production"
aws_region           = "us-east-1"
vpc_cidr             = "10.2.0.0/16"
public_subnet_cidrs  = ["10.2.1.0/20", "10.2.2.0/20", "10.2.3.0/20"]
private_subnet_cidrs = ["10.2.16.0/18", "10.2.80.0/18", "10.2.144.0/18"]
single_nat_gateway   = false
cluster_version      = "1.28"
on_demand_instance_types = ["t3.large", "t3.xlarge"]
on_demand_desired_size   = 5
on_demand_min_size       = 3
on_demand_max_size       = 10
enable_spot_node_group   = true
instance_class           = "db.r6g.2xlarge"
aurora_reader_count      = 2
redis_node_type          = "cache.r6g.xlarge"
redis_num_nodes          = 3
alert_email              = "ops@longox.io"
root_domain              = "longox.io"
deploy_vault             = true
vault_auto_unseal        = true
deploy_kong              = true
enable_cross_region_replication = true
replication_region       = "us-west-2"
