export type NodeFamily =
  | "trigger"
  | "action"
  | "logic"
  | "ai"
  | "data"
  | "human"
  | "utility"
  | "boundary";

export class NodeType {
  constructor(
    public readonly id: string,
    public readonly family: NodeFamily,
    public readonly name: string,
    public readonly description: string,
    public readonly icon: string,
    public readonly configSchema: Record<string, unknown>,
    public readonly inputSchema: Record<string, unknown>,
    public readonly outputSchema: Record<string, unknown>,
    public readonly defaultConfig: Record<string, unknown>,
  ) {}

  static fromDefinition(def: {
    id: string;
    family: NodeFamily;
    name: string;
    description: string;
    icon: string;
    configSchema: Record<string, unknown>;
    inputSchema: Record<string, unknown>;
    outputSchema: Record<string, unknown>;
    defaultConfig: Record<string, unknown>;
  }): NodeType {
    return new NodeType(
      def.id,
      def.family,
      def.name,
      def.description,
      def.icon,
      def.configSchema,
      def.inputSchema,
      def.outputSchema,
      def.defaultConfig,
    );
  }
}

export const BUILT_IN_NODE_TYPES: NodeType[] = [
  NodeType.fromDefinition({
    id: "trigger.manual",
    family: "trigger",
    name: "Manual Trigger",
    description: "Start a workflow manually",
    icon: "play",
    configSchema: {},
    inputSchema: {},
    outputSchema: { triggeredAt: "string", payload: "object" },
    defaultConfig: {},
  }),
  NodeType.fromDefinition({
    id: "trigger.webhook",
    family: "trigger",
    name: "Webhook",
    description: "Trigger via incoming webhook",
    icon: "webhook",
    configSchema: { path: "string", method: "string" },
    inputSchema: {},
    outputSchema: { body: "object", headers: "object", query: "object" },
    defaultConfig: { method: "POST" },
  }),
  NodeType.fromDefinition({
    id: "trigger.schedule",
    family: "trigger",
    name: "Schedule",
    description: "Run on a cron schedule",
    icon: "clock",
    configSchema: { cron: "string", timezone: "string" },
    inputSchema: {},
    outputSchema: { triggeredAt: "string" },
    defaultConfig: { cron: "0 0 * * *", timezone: "UTC" },
  }),
  NodeType.fromDefinition({
    id: "action.http",
    family: "action",
    name: "HTTP Request",
    description: "Make an HTTP request",
    icon: "globe",
    configSchema: {
      url: "string",
      method: "string",
      headers: "object",
      body: "object",
    },
    inputSchema: {},
    outputSchema: { statusCode: "number", body: "object", headers: "object" },
    defaultConfig: { method: "GET" },
  }),
  NodeType.fromDefinition({
    id: "action.slack",
    family: "action",
    name: "Send Slack Message",
    description: "Post a message to Slack",
    icon: "message-square",
    configSchema: { channel: "string", text: "string" },
    inputSchema: {},
    outputSchema: { ts: "string", ok: "boolean" },
    defaultConfig: { channel: "#general" },
  }),
  NodeType.fromDefinition({
    id: "action.send_email",
    family: "action",
    name: "Send Email",
    description: "Send an email notification",
    icon: "mail",
    configSchema: { to: "string", subject: "string", body: "string" },
    inputSchema: {},
    outputSchema: { messageId: "string", accepted: "boolean" },
    defaultConfig: {},
  }),
  NodeType.fromDefinition({
    id: "action.db_query",
    family: "action",
    name: "Database Query",
    description: "Run a SQL query",
    icon: "database",
    configSchema: { connection: "string", query: "string" },
    inputSchema: {},
    outputSchema: { rows: "array", rowCount: "number" },
    defaultConfig: {},
  }),
  NodeType.fromDefinition({
    id: "action.create_record",
    family: "action",
    name: "Create Record",
    description: "Create a record in a connected system",
    icon: "plus-circle",
    configSchema: { object_type: "string", fields: "object" },
    inputSchema: {},
    outputSchema: { id: "number", createdAt: "string" },
    defaultConfig: {},
  }),
  NodeType.fromDefinition({
    id: "action.salesforce",
    family: "action",
    name: "Salesforce Action",
    description: "Execute a Salesforce operation",
    icon: "zap",
    configSchema: { operation: "string", sobject: "string", data: "object" },
    inputSchema: {},
    outputSchema: { id: "string", success: "boolean" },
    defaultConfig: { operation: "create" },
  }),
  NodeType.fromDefinition({
    id: "action.hubspot",
    family: "action",
    name: "HubSpot Action",
    description: "Execute a HubSpot operation",
    icon: "zap",
    configSchema: { operation: "string", objectType: "string", data: "object" },
    inputSchema: {},
    outputSchema: { id: "string", success: "boolean" },
    defaultConfig: { operation: "create" },
  }),
  NodeType.fromDefinition({
    id: "action.stripe",
    family: "action",
    name: "Stripe Action",
    description: "Execute a Stripe operation",
    icon: "credit-card",
    configSchema: { operation: "string", data: "object" },
    inputSchema: {},
    outputSchema: { id: "string", success: "boolean" },
    defaultConfig: { operation: "create" },
  }),
  NodeType.fromDefinition({
    id: "logic.if",
    family: "logic",
    name: "Condition",
    description: "Branch based on a condition",
    icon: "git-branch",
    configSchema: { field: "string", operator: "string", value: "string" },
    inputSchema: {},
    outputSchema: { branch: "string", evaluated: "boolean" },
    defaultConfig: { operator: "eq" },
  }),
  NodeType.fromDefinition({
    id: "logic.filter",
    family: "logic",
    name: "Filter",
    description: "Filter items based on criteria",
    icon: "filter",
    configSchema: { field: "string", operator: "string", value: "string" },
    inputSchema: {},
    outputSchema: { filtered: "number", total: "number" },
    defaultConfig: {},
  }),
  NodeType.fromDefinition({
    id: "logic.router",
    family: "logic",
    name: "Router",
    description: "Route to different branches",
    icon: "git-branch",
    configSchema: { rules: "array" },
    inputSchema: {},
    outputSchema: { branch: "string", evaluated: "boolean" },
    defaultConfig: {},
  }),
  NodeType.fromDefinition({
    id: "logic.delay",
    family: "logic",
    name: "Delay",
    description: "Wait before proceeding",
    icon: "timer",
    configSchema: { duration: "number", unit: "string" },
    inputSchema: {},
    outputSchema: { delayedMs: "number", resumedAt: "string" },
    defaultConfig: { duration: 1, unit: "seconds" },
  }),
  NodeType.fromDefinition({
    id: "logic.loop",
    family: "logic",
    name: "Loop",
    description: "Iterate over items",
    icon: "repeat",
    configSchema: { iterations: "number" },
    inputSchema: {},
    outputSchema: { iterations: "number", completed: "boolean" },
    defaultConfig: { iterations: 5 },
  }),
  NodeType.fromDefinition({
    id: "ai.prompt",
    family: "ai",
    name: "AI Prompt",
    description: "Send a prompt to an LLM",
    icon: "sparkles",
    configSchema: {
      model: "string",
      systemPrompt: "string",
      maxTokens: "number",
    },
    inputSchema: {},
    outputSchema: { result: "string", modelUsed: "string" },
    defaultConfig: { model: "gpt-4o-mini", maxTokens: 1024 },
  }),
  NodeType.fromDefinition({
    id: "ai.classify",
    family: "ai",
    name: "AI Classify",
    description: "Classify input into categories",
    icon: "tags",
    configSchema: { model: "string", categories: "string" },
    inputSchema: {},
    outputSchema: { category: "string", confidence: "number" },
    defaultConfig: { model: "gpt-4o-mini", categories: "CategoryA,CategoryB" },
  }),
  NodeType.fromDefinition({
    id: "ai.summarize",
    family: "ai",
    name: "AI Summarize",
    description: "Summarize input text",
    icon: "align-left",
    configSchema: { model: "string", maxWords: "number" },
    inputSchema: {},
    outputSchema: { summary: "string", wordCount: "number" },
    defaultConfig: { model: "gpt-4o-mini", maxWords: 100 },
  }),
  NodeType.fromDefinition({
    id: "ai.extract",
    family: "ai",
    name: "AI Extract",
    description: "Extract structured data from input",
    icon: "file-text",
    configSchema: { model: "string", fields: "string" },
    inputSchema: {},
    outputSchema: { extracted: "object", confidence: "number" },
    defaultConfig: { model: "gpt-4o-mini", fields: "vendor,amount,date" },
  }),
  NodeType.fromDefinition({
    id: "data.transform",
    family: "data",
    name: "Transform",
    description: "Transform data shape based on mapping",
    icon: "shuffle",
    configSchema: { mapping: "object" },
    inputSchema: {},
    outputSchema: { transformed: "boolean" },
    defaultConfig: {},
  }),
  NodeType.fromDefinition({
    id: "data.parse_doc",
    family: "data",
    name: "Parse Document",
    description: "Extract text from a document",
    icon: "file",
    configSchema: { format: "string" },
    inputSchema: {},
    outputSchema: { text: "string", pages: "number" },
    defaultConfig: {},
  }),
  NodeType.fromDefinition({
    id: "human.approval",
    family: "human",
    name: "Approval",
    description: "Require human approval to proceed",
    icon: "check-circle",
    configSchema: { approvers: "array", message: "string" },
    inputSchema: {},
    outputSchema: {
      approved: "boolean",
      approvedBy: "string",
      comment: "string",
    },
    defaultConfig: {},
  }),
  NodeType.fromDefinition({
    id: "utility.delay",
    family: "utility",
    name: "Utility Delay",
    description: "Simple delay utility",
    icon: "clock",
    configSchema: { seconds: "number" },
    inputSchema: {},
    outputSchema: { elapsed: "number" },
    defaultConfig: { seconds: 5 },
  }),
  NodeType.fromDefinition({
    id: "utility.debug",
    family: "utility",
    name: "Debug Log",
    description: "Log data for debugging",
    icon: "terminal",
    configSchema: { message: "string" },
    inputSchema: {},
    outputSchema: { logged: "boolean" },
    defaultConfig: {},
  }),
];
