apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-control

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"

images:
  - name: autoflow/api-gateway
    newTag: staging
  - name: autoflow/execution-service
    newTag: staging
