apiVersion: v1
kind: Namespace
metadata:
  name: platform-control
  labels:
    app.kubernetes.io/part-of: longox
---

apiVersion: v1
kind: Namespace
metadata:
  name: platform-services
  labels:
    app.kubernetes.io/part-of: longox
---

apiVersion: v1
kind: Namespace
metadata:
  name: platform-execution
  labels:
    app.kubernetes.io/part-of: longox
---

apiVersion: v1
kind: Namespace
metadata:
  name: platform-observability
  labels:
    app.kubernetes.io/part-of: longox
