apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels: {{- include "longox.labels" $ | nindent 4 }}
type: Opaque
stringData:
  database_url: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Values.postgresql.auth.database | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  labels: {{- include "longox.labels" $ | nindent 4 }}
type: Opaque
stringData:
  secret: {{ randAlphaNum 32 | quote }}
