environment          = "staging"
aws_region           = "us-east-1"
vpc_cidr             = "10.1.0.0/16"
public_subnet_cidrs  = ["10.1.1.0/20", "10.1.2.0/20", "10.1.3.0/20"]
private_subnet_cidrs = ["10.1.16.0/18", "10.1.80.0/18", "10.1.144.0/18"]
single_nat_gateway   = false
cluster_version      = "1.28"
on_demand_instance_types = ["t3.large"]
on_demand_desired_size   = 3
on_demand_min_size       = 2
on_demand_max_size       = 6
enable_spot_node_group   = true
instance_class           = "db.r6g.large"
aurora_reader_count      = 1
redis_node_type          = "cache.r6g.large"
redis_num_nodes          = 2
alert_email              = "devops@longox.io"
root_domain              = "longox.io"
deploy_vault             = true
vault_auto_unseal        = true
deploy_kong              = true
enable_cross_region_replication = false
